# Typ Pfad                    Modus  Benutzer Gruppe Alter Argument
d     /var/lib/soju           0750   soju    soju    -     -
d     /var/log/soju           0750   soju    soju    -     -
d     /run/soju               0750   soju    soju    -     -
